from __future__ import annotations

class ProfilerCircuit:
    @classmethod
    def from_adapter_data(
        cls,
        ops: list[dict],
        deps: list[tuple[int, int]],
        qubit_count: int,
        metadata: dict,
        qubit_positions: list[dict] | None = None,
        hooks: list[dict] | None = None,
    ) -> ProfilerCircuit: ...
    @property
    def qubit_count(self) -> int: ...
    @property
    def op_count(self) -> int: ...
    @property
    def t_count(self) -> int: ...
    @property
    def clifford_count(self) -> int: ...
    @property
    def rotation_count(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def source_framework(self) -> str: ...
    def to_json(self) -> str: ...
    def save_json(self, path: str) -> None: ...

class HardwareModel:
    @classmethod
    def from_toml(cls, path: str) -> HardwareModel: ...
    @classmethod
    def from_toml_str(cls, toml: str) -> HardwareModel: ...
    @property
    def name(self) -> str: ...
    @property
    def code_distance(self) -> int: ...
    @property
    def factory_count(self) -> int: ...
    @property
    def factory_type(self) -> str: ...
    @property
    def buffer_capacity(self) -> int: ...

class ExecutionProfile:
    @property
    def total_cycles(self) -> int: ...
    @property
    def resolution(self) -> int: ...
    @property
    def factory_utilization(self) -> list[float]: ...
    @property
    def buffer_occupancy(self) -> list[int]: ...
    @property
    def stall_events(self) -> list[StallRecord]: ...
    @property
    def injection_errors(self) -> int: ...
    @property
    def fixups_inserted(self) -> int: ...
    @property
    def critical_path_extension(self) -> int: ...
    def to_json(self) -> str: ...
    def save_json(self, path: str) -> None: ...

class Trace:
    @property
    def total_cycles(self) -> int: ...
    @property
    def seed(self) -> int: ...
    @property
    def truncated(self) -> bool: ...
    @property
    def event_count(self) -> int: ...
    @property
    def schema_version(self) -> str: ...
    def to_json(self) -> str: ...
    def save_json(self, path: str) -> None: ...

class StallRecord:
    @property
    def cycle(self) -> int: ...
    @property
    def gate_id(self) -> int: ...
    @property
    def wait_cycles(self) -> int: ...

def profile(
    circuit: ProfilerCircuit,
    hw: HardwareModel,
    *,
    seed: int = 42,
    max_cycles: int | None = None,
    resolution: int = 10,
) -> ExecutionProfile: ...
def trace(
    circuit: ProfilerCircuit,
    hw: HardwareModel,
    *,
    seed: int = 42,
    max_cycles: int | None = None,
) -> Trace: ...
def read_json(path: str) -> ProfilerCircuit: ...
def read_json_str(json: str) -> ProfilerCircuit: ...

__version__: str

class ValidationError(ValueError): ...
class HardwareModelError(ValueError): ...
class EngineError(RuntimeError): ...
class ParseError(ValueError): ...
